# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/nextcloud.barye.cloudns.asia
cert = /etc/letsencrypt/live/nextcloud.barye.cloudns.asia/cert.pem
privkey = /etc/letsencrypt/live/nextcloud.barye.cloudns.asia/privkey.pem
chain = /etc/letsencrypt/live/nextcloud.barye.cloudns.asia/chain.pem
fullchain = /etc/letsencrypt/live/nextcloud.barye.cloudns.asia/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = REDACTED
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
